package com.lhhs.workflow.dao.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.lhhs.loan.common.shared.page.BaseObject;

public class ActServiceVO extends BaseObject{
	private String id;
	public ActServiceVO(){
		super();
	}
	public ActServiceVO(TaskVo task){
		this.procInsId = task.getProcInsId();
		//this.actDesc = task.getActDesc();
		this.actName = task.getTitle();
		this.actStatus = task.getStatus();
		this.branchComId = task.getBranchCom();
		this.branchOffic = task.getSalesOffice();
		this.createDate = new Date();
		this.operator = task.getOperator();
		this.operatorName = task.getOperatorName();
		this.organiser  = task.getOrganiser();
		this.organiserName = task.getOrganiserName();
		this.procdefkey = task.getProcDefKey();
		this.productDptId = task.getProductDpt();
		this.productLineId = task.getProductLine();
		if(task.getCategory()!=null){
			this.sysType = task.getCategory().toUpperCase();
		}
		this.businessid = task.getBusinessId();
		//合作伙伴暂时无法取到zhi
		this.partner =task.getPartner();
		this.amount=task.getAmount();
		this.orderNo=task.getOrderNo();
		this.field1=task.getField1();
		this.field2=task.getField2();
		this.field3=task.getField3();
		this.field4=task.getField4();
	}
    /**
	 * 
	 */
	private static final long serialVersionUID = -47131515434137795L;
	   

    private BigDecimal oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.PROC_INS_ID
     *
     * @mbggenerated
     */
    private String procInsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.PRODUCT_DPT
     *
     * @mbggenerated
     */
    private String productDpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.PRODUCT_LINE
     *
     * @mbggenerated
     */
    private String productLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.BRANCH_COM
     *
     * @mbggenerated
     */
    private String branchCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.PARTNER
     *
     * @mbggenerated
     */
    private String partner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.ACT_NAME
     *
     * @mbggenerated
     */
    private String actName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.BRANCH_OFFIC
     *
     * @mbggenerated
     */
    private String branchOffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.ORGANISER_NAME
     *
     * @mbggenerated
     */
    private String organiserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.ORGANISER
     *
     * @mbggenerated
     */
    private String organiser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.PROCDEFKEY
     *
     * @mbggenerated
     */
    private String procdefkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.ACT_DESC
     *
     * @mbggenerated
     */
    private String actDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.PRODUCT_DPT_ID
     *
     * @mbggenerated
     */
    private String productDptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.PRODUCT_LINE_ID
     *
     * @mbggenerated
     */
    private String productLineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.BRANCH_COM_ID
     *
     * @mbggenerated
     */
    private String branchComId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.SYS_TYPE
     *
     * @mbggenerated
     */
    private String sysType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_SERVICE.ACT_STATUS
     *
     * @mbggenerated
     */
    private String actStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_SERVICE.OID
     *
     * @return the value of ACT_SERVICE.OID
     *
     * @mbggenerated
     */
    private String businessid;
    private Date endDate;
    private String branchOfficId;
    /**
     * 行政组织名称
     */
    private String departmentName; 
    /**
	 * 金额
	 */
	private String amount;
	/**
	 * 订单单号
	 */
	private String orderNo;
	
    private String field1;

    private String field2;

    private String field3;

    private String field4;
    public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public String getBranchOfficId() {
		return branchOfficId;
	}
	public void setBranchOfficId(String branchOfficId) {
		this.branchOfficId = branchOfficId;
	}
	public String getBusinessid() {
		return businessid;
	}
	public void setBusinessid(String businessid) {
		this.businessid = businessid;
	}
	public BigDecimal getOid() {
        return oid;
    }

 
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    public String getProcInsId() {
        return procInsId;
    }

    public void setProcInsId(String procInsId) {
        this.procInsId = procInsId == null ? null : procInsId.trim();
    }

    public String getProductDpt() {
        return productDpt;
    }

    public void setProductDpt(String productDpt) {
        this.productDpt = productDpt == null ? null : productDpt.trim();
    }

    public String getProductLine() {
        return productLine;
    }

    public void setProductLine(String productLine) {
        this.productLine = productLine == null ? null : productLine.trim();
    }

    public String getBranchCom() {
        return branchCom;
    }

    public void setBranchCom(String branchCom) {
        this.branchCom = branchCom == null ? null : branchCom.trim();
    }

    public String getPartner() {
        return partner;
    }

    public void setPartner(String partner) {
        this.partner = partner == null ? null : partner.trim();
    }

    public String getActName() {
        return actName;
    }

    public void setActName(String actName) {
        this.actName = actName == null ? null : actName.trim();
    }

    public String getBranchOffic() {
        return branchOffic;
    }

    public void setBranchOffic(String branchOffic) {
        this.branchOffic = branchOffic == null ? null : branchOffic.trim();
    }

    public String getOrganiserName() {
        return organiserName;
    }

    public void setOrganiserName(String organiserName) {
        this.organiserName = organiserName == null ? null : organiserName.trim();
    }

    public String getOperatorName() {
        return operatorName;
    }

    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    public String getOrganiser() {
        return organiser;
    }


    public void setOrganiser(String organiser) {
        this.organiser = organiser == null ? null : organiser.trim();
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    public String getProcdefkey() {
        return procdefkey;
    }

    public void setProcdefkey(String procdefkey) {
        this.procdefkey = procdefkey == null ? null : procdefkey.trim();
    }

    public String getActDesc() {
        return actDesc;
    }

    public void setActDesc(String actDesc) {
        this.actDesc = actDesc == null ? null : actDesc.trim();
    }

    public String getProductDptId() {
        return productDptId;
    }

    public void setProductDptId(String productDptId) {
        this.productDptId = productDptId == null ? null : productDptId.trim();
    }

    public String getProductLineId() {
        return productLineId;
    }

    public void setProductLineId(String productLineId) {
        this.productLineId = productLineId == null ? null : productLineId.trim();
    }

    public String getBranchComId() {
        return branchComId;
    }

    public void setBranchComId(String branchComId) {
        this.branchComId = branchComId == null ? null : branchComId.trim();
    }

    public String getSysType() {
        return sysType;
    }

    public void setSysType(String sysType) {
        this.sysType = sysType == null ? null : sysType.trim();
    }


    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getActStatus() {
        return actStatus;
    }

    public void setActStatus(String actStatus) {
        this.actStatus = actStatus == null ? null : actStatus.trim();
    }
	public String getDepartmentName() {
		return departmentName;
	}
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}
	public String getAmount() {
		return amount;
	}
	public void setAmount(String amount) {
		this.amount = amount;
	}
	public String getOrderNo() {
		return orderNo;
	}
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
	public String getField1() {
		return field1;
	}
	public void setField1(String field1) {
		this.field1 = field1;
	}
	public String getField2() {
		return field2;
	}
	public void setField2(String field2) {
		this.field2 = field2;
	}
	public String getField3() {
		return field3;
	}
	public void setField3(String field3) {
		this.field3 = field3;
	}
	public String getField4() {
		return field4;
	}
	public void setField4(String field4) {
		this.field4 = field4;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}


}