package com.lhhs.workflow.dao.domain;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.lhhs.loan.common.shared.page.BaseObject;

public class VActHaddoVO extends BaseObject{
    /**
	 * 
	 */
	private static final long serialVersionUID = -2088895588071330078L;

	private String procDefId;
	private String formKey;
	private String formUrl;
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.TASK_ID
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.TASK_NAME
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.TASK_DEF_KEY
     *
     * @mbggenerated
     */
    private String taskDefKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PASS
     *
     * @mbggenerated
     */
    private String pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PASS_NAME
     *
     * @mbggenerated
     */
    private String passName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.TASK_CREATE_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date taskCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.TASK_END_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@JSONField (format="yyyy-MM-dd HH:mm:ss") 
    private Date taskEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PROC_INS_ID
     *
     * @mbggenerated
     */
    private String procInsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.ASSIGNEE
     *
     * @mbggenerated
     */
    private String assignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.ASSIGNEE_NAME
     *
     * @mbggenerated
     */
    private String assigneeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.NEXT_ASSIGNEE
     *
     * @mbggenerated
     */
    private String nextAssignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.NEXT_ASSIGNEE_NAME
     *
     * @mbggenerated
     */
    private String nextAssigneeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.MSG
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PROC_DEF_KEY
     *
     * @mbggenerated
     */
    private String procDefKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PROC_NAME
     *
     * @mbggenerated
     */
    private String procName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.ORGANISER
     *
     * @mbggenerated
     */
    private String organiser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.ORGANISER_NAME
     *
     * @mbggenerated
     */
    private String organiserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.BUSINESS_ID
     *
     * @mbggenerated
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.IP
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.CHANNEL
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.FIELD1
     *
     * @mbggenerated
     */
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.FIELD2
     *
     * @mbggenerated
     */
    private String field2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.FIELD3
     *
     * @mbggenerated
     */
    private String field3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.FIELD4
     *
     * @mbggenerated
     */
    private String field4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.OFFICID
     *
     * @mbggenerated
     */
    private String officid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.SALESORGID
     *
     * @mbggenerated
     */
    private String salesorgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.OAORGID
     *
     * @mbggenerated
     */
    private String oaorgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PRODUCTIINEID
     *
     * @mbggenerated
     */
    private String productiineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PRODUCT_DPT
     *
     * @mbggenerated
     */
    private String productDpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PRODUCT_LINE
     *
     * @mbggenerated
     */
    private String productLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.BRANCH_COM
     *
     * @mbggenerated
     */
    private String branchCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PARTNER
     *
     * @mbggenerated
     */
    private String partner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.ACT_NAME
     *
     * @mbggenerated
     */
    private String actName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.BRANCH_OFFIC
     *
     * @mbggenerated
     */
    private String branchOffic;

    private String branchOfficId;
    
    
    public String getBranchOfficId() {
		return branchOfficId;
	}

	public void setBranchOfficId(String branchOfficId) {
		this.branchOfficId = branchOfficId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PROCDEFKEY
     *
     * @mbggenerated
     */
    private String procdefkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.ACT_DESC
     *
     * @mbggenerated
     */
    private String actDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PRODUCT_DPT_ID
     *
     * @mbggenerated
     */
    private String productDptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.PRODUCT_LINE_ID
     *
     * @mbggenerated
     */
    private String productLineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.BRANCH_COM_ID
     *
     * @mbggenerated
     */
    private String branchComId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.SYS_TYPE
     *
     * @mbggenerated
     */
    private String sysType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.CREATE_DATE
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@JSONField (format="yyyy-MM-dd HH:mm:ss")
    private Date createDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@JSONField (format="yyyy-MM-dd HH:mm:ss")
    private Date endDate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.ACT_STATUS
     *
     * @mbggenerated
     */
    private String actStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ACT_HADDO.BUSINESSID
     *
     * @mbggenerated
     */
    private String businessid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.ID
     *
     * @return the value of V_ACT_HADDO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.ID
     *
     * @param id the value for V_ACT_HADDO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.TASK_ID
     *
     * @return the value of V_ACT_HADDO.TASK_ID
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.TASK_ID
     *
     * @param taskId the value for V_ACT_HADDO.TASK_ID
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.TASK_NAME
     *
     * @return the value of V_ACT_HADDO.TASK_NAME
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.TASK_NAME
     *
     * @param taskName the value for V_ACT_HADDO.TASK_NAME
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.TASK_DEF_KEY
     *
     * @return the value of V_ACT_HADDO.TASK_DEF_KEY
     *
     * @mbggenerated
     */
    public String getTaskDefKey() {
        return taskDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.TASK_DEF_KEY
     *
     * @param taskDefKey the value for V_ACT_HADDO.TASK_DEF_KEY
     *
     * @mbggenerated
     */
    public void setTaskDefKey(String taskDefKey) {
        this.taskDefKey = taskDefKey == null ? null : taskDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PASS
     *
     * @return the value of V_ACT_HADDO.PASS
     *
     * @mbggenerated
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PASS
     *
     * @param pass the value for V_ACT_HADDO.PASS
     *
     * @mbggenerated
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PASS_NAME
     *
     * @return the value of V_ACT_HADDO.PASS_NAME
     *
     * @mbggenerated
     */
    public String getPassName() {
        return passName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PASS_NAME
     *
     * @param passName the value for V_ACT_HADDO.PASS_NAME
     *
     * @mbggenerated
     */
    public void setPassName(String passName) {
        this.passName = passName == null ? null : passName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.TASK_CREATE_DATE
     *
     * @return the value of V_ACT_HADDO.TASK_CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getTaskCreateDate() {
        return taskCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.TASK_CREATE_DATE
     *
     * @param taskCreateDate the value for V_ACT_HADDO.TASK_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setTaskCreateDate(Date taskCreateDate) {
        this.taskCreateDate = taskCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.TASK_END_DATE
     *
     * @return the value of V_ACT_HADDO.TASK_END_DATE
     *
     * @mbggenerated
     */
    public Date getTaskEndDate() {
        return taskEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.TASK_END_DATE
     *
     * @param taskEndDate the value for V_ACT_HADDO.TASK_END_DATE
     *
     * @mbggenerated
     */
    public void setTaskEndDate(Date taskEndDate) {
        this.taskEndDate = taskEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PROC_INS_ID
     *
     * @return the value of V_ACT_HADDO.PROC_INS_ID
     *
     * @mbggenerated
     */
    public String getProcInsId() {
        return procInsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PROC_INS_ID
     *
     * @param procInsId the value for V_ACT_HADDO.PROC_INS_ID
     *
     * @mbggenerated
     */
    public void setProcInsId(String procInsId) {
        this.procInsId = procInsId == null ? null : procInsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.ASSIGNEE
     *
     * @return the value of V_ACT_HADDO.ASSIGNEE
     *
     * @mbggenerated
     */
    public String getAssignee() {
        return assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.ASSIGNEE
     *
     * @param assignee the value for V_ACT_HADDO.ASSIGNEE
     *
     * @mbggenerated
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee == null ? null : assignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.ASSIGNEE_NAME
     *
     * @return the value of V_ACT_HADDO.ASSIGNEE_NAME
     *
     * @mbggenerated
     */
    public String getAssigneeName() {
        return assigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.ASSIGNEE_NAME
     *
     * @param assigneeName the value for V_ACT_HADDO.ASSIGNEE_NAME
     *
     * @mbggenerated
     */
    public void setAssigneeName(String assigneeName) {
        this.assigneeName = assigneeName == null ? null : assigneeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.NEXT_ASSIGNEE
     *
     * @return the value of V_ACT_HADDO.NEXT_ASSIGNEE
     *
     * @mbggenerated
     */
    public String getNextAssignee() {
        return nextAssignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.NEXT_ASSIGNEE
     *
     * @param nextAssignee the value for V_ACT_HADDO.NEXT_ASSIGNEE
     *
     * @mbggenerated
     */
    public void setNextAssignee(String nextAssignee) {
        this.nextAssignee = nextAssignee == null ? null : nextAssignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.NEXT_ASSIGNEE_NAME
     *
     * @return the value of V_ACT_HADDO.NEXT_ASSIGNEE_NAME
     *
     * @mbggenerated
     */
    public String getNextAssigneeName() {
        return nextAssigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.NEXT_ASSIGNEE_NAME
     *
     * @param nextAssigneeName the value for V_ACT_HADDO.NEXT_ASSIGNEE_NAME
     *
     * @mbggenerated
     */
    public void setNextAssigneeName(String nextAssigneeName) {
        this.nextAssigneeName = nextAssigneeName == null ? null : nextAssigneeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.MSG
     *
     * @return the value of V_ACT_HADDO.MSG
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.MSG
     *
     * @param msg the value for V_ACT_HADDO.MSG
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PROC_DEF_KEY
     *
     * @return the value of V_ACT_HADDO.PROC_DEF_KEY
     *
     * @mbggenerated
     */
    public String getProcDefKey() {
        return procDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PROC_DEF_KEY
     *
     * @param procDefKey the value for V_ACT_HADDO.PROC_DEF_KEY
     *
     * @mbggenerated
     */
    public void setProcDefKey(String procDefKey) {
        this.procDefKey = procDefKey == null ? null : procDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PROC_NAME
     *
     * @return the value of V_ACT_HADDO.PROC_NAME
     *
     * @mbggenerated
     */
    public String getProcName() {
        return procName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PROC_NAME
     *
     * @param procName the value for V_ACT_HADDO.PROC_NAME
     *
     * @mbggenerated
     */
    public void setProcName(String procName) {
        this.procName = procName == null ? null : procName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.ORGANISER
     *
     * @return the value of V_ACT_HADDO.ORGANISER
     *
     * @mbggenerated
     */
    public String getOrganiser() {
        return organiser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.ORGANISER
     *
     * @param organiser the value for V_ACT_HADDO.ORGANISER
     *
     * @mbggenerated
     */
    public void setOrganiser(String organiser) {
        this.organiser = organiser == null ? null : organiser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.ORGANISER_NAME
     *
     * @return the value of V_ACT_HADDO.ORGANISER_NAME
     *
     * @mbggenerated
     */
    public String getOrganiserName() {
        return organiserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.ORGANISER_NAME
     *
     * @param organiserName the value for V_ACT_HADDO.ORGANISER_NAME
     *
     * @mbggenerated
     */
    public void setOrganiserName(String organiserName) {
        this.organiserName = organiserName == null ? null : organiserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.BUSINESS_ID
     *
     * @return the value of V_ACT_HADDO.BUSINESS_ID
     *
     * @mbggenerated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.BUSINESS_ID
     *
     * @param businessId the value for V_ACT_HADDO.BUSINESS_ID
     *
     * @mbggenerated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.STATUS
     *
     * @return the value of V_ACT_HADDO.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.STATUS
     *
     * @param status the value for V_ACT_HADDO.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.IP
     *
     * @return the value of V_ACT_HADDO.IP
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.IP
     *
     * @param ip the value for V_ACT_HADDO.IP
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.CHANNEL
     *
     * @return the value of V_ACT_HADDO.CHANNEL
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.CHANNEL
     *
     * @param channel the value for V_ACT_HADDO.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.FIELD1
     *
     * @return the value of V_ACT_HADDO.FIELD1
     *
     * @mbggenerated
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.FIELD1
     *
     * @param field1 the value for V_ACT_HADDO.FIELD1
     *
     * @mbggenerated
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.FIELD2
     *
     * @return the value of V_ACT_HADDO.FIELD2
     *
     * @mbggenerated
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.FIELD2
     *
     * @param field2 the value for V_ACT_HADDO.FIELD2
     *
     * @mbggenerated
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.FIELD3
     *
     * @return the value of V_ACT_HADDO.FIELD3
     *
     * @mbggenerated
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.FIELD3
     *
     * @param field3 the value for V_ACT_HADDO.FIELD3
     *
     * @mbggenerated
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.FIELD4
     *
     * @return the value of V_ACT_HADDO.FIELD4
     *
     * @mbggenerated
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.FIELD4
     *
     * @param field4 the value for V_ACT_HADDO.FIELD4
     *
     * @mbggenerated
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.OFFICID
     *
     * @return the value of V_ACT_HADDO.OFFICID
     *
     * @mbggenerated
     */
    public String getOfficid() {
        return officid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.OFFICID
     *
     * @param officid the value for V_ACT_HADDO.OFFICID
     *
     * @mbggenerated
     */
    public void setOfficid(String officid) {
        this.officid = officid == null ? null : officid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.SALESORGID
     *
     * @return the value of V_ACT_HADDO.SALESORGID
     *
     * @mbggenerated
     */
    public String getSalesorgid() {
        return salesorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.SALESORGID
     *
     * @param salesorgid the value for V_ACT_HADDO.SALESORGID
     *
     * @mbggenerated
     */
    public void setSalesorgid(String salesorgid) {
        this.salesorgid = salesorgid == null ? null : salesorgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.OAORGID
     *
     * @return the value of V_ACT_HADDO.OAORGID
     *
     * @mbggenerated
     */
    public String getOaorgid() {
        return oaorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.OAORGID
     *
     * @param oaorgid the value for V_ACT_HADDO.OAORGID
     *
     * @mbggenerated
     */
    public void setOaorgid(String oaorgid) {
        this.oaorgid = oaorgid == null ? null : oaorgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PRODUCTIINEID
     *
     * @return the value of V_ACT_HADDO.PRODUCTIINEID
     *
     * @mbggenerated
     */
    public String getProductiineid() {
        return productiineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PRODUCTIINEID
     *
     * @param productiineid the value for V_ACT_HADDO.PRODUCTIINEID
     *
     * @mbggenerated
     */
    public void setProductiineid(String productiineid) {
        this.productiineid = productiineid == null ? null : productiineid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.OPERATOR
     *
     * @return the value of V_ACT_HADDO.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.OPERATOR
     *
     * @param operator the value for V_ACT_HADDO.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.OPERATOR_NAME
     *
     * @return the value of V_ACT_HADDO.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.OPERATOR_NAME
     *
     * @param operatorName the value for V_ACT_HADDO.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PRODUCT_DPT
     *
     * @return the value of V_ACT_HADDO.PRODUCT_DPT
     *
     * @mbggenerated
     */
    public String getProductDpt() {
        return productDpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PRODUCT_DPT
     *
     * @param productDpt the value for V_ACT_HADDO.PRODUCT_DPT
     *
     * @mbggenerated
     */
    public void setProductDpt(String productDpt) {
        this.productDpt = productDpt == null ? null : productDpt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PRODUCT_LINE
     *
     * @return the value of V_ACT_HADDO.PRODUCT_LINE
     *
     * @mbggenerated
     */
    public String getProductLine() {
        return productLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PRODUCT_LINE
     *
     * @param productLine the value for V_ACT_HADDO.PRODUCT_LINE
     *
     * @mbggenerated
     */
    public void setProductLine(String productLine) {
        this.productLine = productLine == null ? null : productLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.BRANCH_COM
     *
     * @return the value of V_ACT_HADDO.BRANCH_COM
     *
     * @mbggenerated
     */
    public String getBranchCom() {
        return branchCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.BRANCH_COM
     *
     * @param branchCom the value for V_ACT_HADDO.BRANCH_COM
     *
     * @mbggenerated
     */
    public void setBranchCom(String branchCom) {
        this.branchCom = branchCom == null ? null : branchCom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PARTNER
     *
     * @return the value of V_ACT_HADDO.PARTNER
     *
     * @mbggenerated
     */
    public String getPartner() {
        return partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PARTNER
     *
     * @param partner the value for V_ACT_HADDO.PARTNER
     *
     * @mbggenerated
     */
    public void setPartner(String partner) {
        this.partner = partner == null ? null : partner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.ACT_NAME
     *
     * @return the value of V_ACT_HADDO.ACT_NAME
     *
     * @mbggenerated
     */
    public String getActName() {
        return actName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.ACT_NAME
     *
     * @param actName the value for V_ACT_HADDO.ACT_NAME
     *
     * @mbggenerated
     */
    public void setActName(String actName) {
        this.actName = actName == null ? null : actName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.BRANCH_OFFIC
     *
     * @return the value of V_ACT_HADDO.BRANCH_OFFIC
     *
     * @mbggenerated
     */
    public String getBranchOffic() {
        return branchOffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.BRANCH_OFFIC
     *
     * @param branchOffic the value for V_ACT_HADDO.BRANCH_OFFIC
     *
     * @mbggenerated
     */
    public void setBranchOffic(String branchOffic) {
        this.branchOffic = branchOffic == null ? null : branchOffic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PROCDEFKEY
     *
     * @return the value of V_ACT_HADDO.PROCDEFKEY
     *
     * @mbggenerated
     */
    public String getProcdefkey() {
        return procdefkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PROCDEFKEY
     *
     * @param procdefkey the value for V_ACT_HADDO.PROCDEFKEY
     *
     * @mbggenerated
     */
    public void setProcdefkey(String procdefkey) {
        this.procdefkey = procdefkey == null ? null : procdefkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.ACT_DESC
     *
     * @return the value of V_ACT_HADDO.ACT_DESC
     *
     * @mbggenerated
     */
    public String getActDesc() {
        return actDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.ACT_DESC
     *
     * @param actDesc the value for V_ACT_HADDO.ACT_DESC
     *
     * @mbggenerated
     */
    public void setActDesc(String actDesc) {
        this.actDesc = actDesc == null ? null : actDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PRODUCT_DPT_ID
     *
     * @return the value of V_ACT_HADDO.PRODUCT_DPT_ID
     *
     * @mbggenerated
     */
    public String getProductDptId() {
        return productDptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PRODUCT_DPT_ID
     *
     * @param productDptId the value for V_ACT_HADDO.PRODUCT_DPT_ID
     *
     * @mbggenerated
     */
    public void setProductDptId(String productDptId) {
        this.productDptId = productDptId == null ? null : productDptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.PRODUCT_LINE_ID
     *
     * @return the value of V_ACT_HADDO.PRODUCT_LINE_ID
     *
     * @mbggenerated
     */
    public String getProductLineId() {
        return productLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.PRODUCT_LINE_ID
     *
     * @param productLineId the value for V_ACT_HADDO.PRODUCT_LINE_ID
     *
     * @mbggenerated
     */
    public void setProductLineId(String productLineId) {
        this.productLineId = productLineId == null ? null : productLineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.BRANCH_COM_ID
     *
     * @return the value of V_ACT_HADDO.BRANCH_COM_ID
     *
     * @mbggenerated
     */
    public String getBranchComId() {
        return branchComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.BRANCH_COM_ID
     *
     * @param branchComId the value for V_ACT_HADDO.BRANCH_COM_ID
     *
     * @mbggenerated
     */
    public void setBranchComId(String branchComId) {
        this.branchComId = branchComId == null ? null : branchComId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.SYS_TYPE
     *
     * @return the value of V_ACT_HADDO.SYS_TYPE
     *
     * @mbggenerated
     */
    public String getSysType() {
        return sysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.SYS_TYPE
     *
     * @param sysType the value for V_ACT_HADDO.SYS_TYPE
     *
     * @mbggenerated
     */
    public void setSysType(String sysType) {
        this.sysType = sysType == null ? null : sysType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.CREATE_DATE
     *
     * @return the value of V_ACT_HADDO.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.CREATE_DATE
     *
     * @param createDate the value for V_ACT_HADDO.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.ACT_STATUS
     *
     * @return the value of V_ACT_HADDO.ACT_STATUS
     *
     * @mbggenerated
     */
    public String getActStatus() {
        return actStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.ACT_STATUS
     *
     * @param actStatus the value for V_ACT_HADDO.ACT_STATUS
     *
     * @mbggenerated
     */
    public void setActStatus(String actStatus) {
        this.actStatus = actStatus == null ? null : actStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ACT_HADDO.BUSINESSID
     *
     * @return the value of V_ACT_HADDO.BUSINESSID
     *
     * @mbggenerated
     */
    public String getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ACT_HADDO.BUSINESSID
     *
     * @param businessid the value for V_ACT_HADDO.BUSINESSID
     *
     * @mbggenerated
     */
    public void setBusinessid(String businessid) {
        this.businessid = businessid == null ? null : businessid.trim();
    }

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getProcDefId() {
		return procDefId;
	}

	public void setProcDefId(String procDefId) {
		this.procDefId = procDefId;
	}

	public String getFormKey() {
		return formKey;
	}

	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}

	public String getFormUrl() {
		return formUrl;
	}

	public void setFormUrl(String formUrl) {
		this.formUrl = formUrl;
	}
    
}